#!/usr/bin/env sh

cap="$(cat /sys/class/power_supply/BAT0/capacity)"
stat="$(cat /sys/class/power_supply/BAT0/status)"

icon="󰂃"

[[ "${stat}" == "Charging" ]] && icon="󰂄"

printf "%s %s%%" "${icon}" "${cap}"
