#!/usr/bin/env sh

mute="$(pactl get-sink-mute @DEFAULT_SINK@)"
vol="$(pactl get-sink-volume @DEFAULT_SINK@ \
  | grep "Volume:" | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')"

icon="󱄡"

[[ $mute = "Mute: yes" ]] && icon="󰸈"

printf "%s %s%%" "${icon}" "${vol}"
