#!/usr/bin/env bash

RST="\\[\\033[00m\\]"
RED="${RST}\\[\\033[00;31m\\]"
GRN="${RST}\\[\\033[00;32m\\]"
YLW="${RST}\\[\\033[00;33m\\]"
BLU="${RST}\\[\\033[00;34m\\]"
PUR="${RST}\\[\\033[00;35m\\]"

PGB="\$(git branch 2> /dev/null | sed -e \
  '/^[^*]/d' -e 's/* \(.*\)/ ${BLU}(${GRN}\1${BLU})/')"

PS1="${BLU}${PUR}\u${RED}@${BLU}\h ${YLW}\W${RST}${BLU}${PGB}${RED} »› ${RST}"
export PS1
