#!/usr/bin/env fish

set -l capacity (cat /sys/class/power_supply/BAT0/capacity)
set -l battery_status (cat /sys/class/power_supply/BAT0/status)

if [ $battery_status = "Charging" ]
  set -g icons "󰢜" "󰂆" "󰂇" "󰂈" "󰢝" "󰂉" "󰢞" "󰂊" "󰂋" "󰂅"
else
  set -g icons "󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹"
end

if [ $capacity -ge 99 ]; set -g icon $icons[-1]
else if [ $capacity -lt 99 -a $capacity -ge 90 ]
  set -g icon $icons[-2]
else if [ $capacity -lt 90 -a $capacity -ge 80 ]
  set -g icon $icons[-3]
else if [ $capacity -lt 80 -a $capacity -ge 70 ]
  set -g icon $icons[-4]
else if [ $capacity -lt 70 -a $capacity -ge 60 ]
  set -g icon $icons[-5]
else if [ $capacity -lt 60 -a $capacity -ge 50 ]
  set -g icon $icons[-6]
else if [ $capacity -lt 50 -a $capacity -ge 40 ]
  set -g icon $icons[-7]
else if [ $capacity -lt 40 -a $capacity -ge 30 ]
  set -g icon $icons[-8]
else if [ $capacity -lt 30 -a $capacity -ge 20 ]
  set -g icon $icons[-9]
else; set -g icon $icons[-10]; end

printf "%s %s%%" $icon $capacity
