#!/usr/bin/env fish

argparse --ignore-unknown \
  "u/up" "d/down" "l/level=" "s/set=" -- $argv

not type -q brightnessctl && exit

set -q _flag_set && brightnessctl --quiet set "$_flag_set%" && exit

if set -q _flag_level
  if set -q _flag_up
    brightnessctl --quiet set "+$_flag_level%"
  else if set -q _flag_down
    brightnessctl --quiet set "$_flag_level%-"
  end
end
