#!/usr/bin/env fish

set -l sldir $HOME/.dotfiles/suckless

test -d $sldir || mkdir -p $sldir

set -l dwmflexdir $sldir/dmwflexipatch
set -l finalizerdir $sldir/finalizer
set -l destdir $sldir/dwm

git clone https://github.com/bakkeby/dwm-flexipatch.git $dwmflexdir

set -l patches \
  "VIEWONTAG" "PERTAG" "AUTOSTART" \
  "ATTACHBOTTOM" "ALWAYSCENTER" "ALT_TAB" \
  "VANITYGAPS" "XRDB" "MOVESTACK" "RESTARTSIG" \
  "BAR_STATUSPADDING" "BAR_STATUSCOLORS" "BAR_STATUSALLMONS"

set -l patchfile $dwmflexdir/patches.def.h

for patch in $patches
  sed -i "s#define ${patch}_PATCH 0/s#define ${patch}_PATCH 1" $patchfile
end

cd $dwmflexdir
make && sudo make clean install
cd -

git clone https://github.com/bakkeby/flexipatch-finalizer.git $finalizerdir
cd $finalizerdir
./flexipatch-finalizer.sh -r -d $dwmflexdir -o $destdir

cd $destdir
make && sudo make clean install
