#!/usr/bin/env fish

set -l sldir $HOME/.dotfiles/suckless

set -l dwmflexdir $sldir/dmwflexipatch
set -l flexfinalizerdir $sldir/flexfinalizer
set -l destdir $sldir/dwm

git clone https://github.com/bakkeby/dwm-flexipatch.git $dwmflexdir

set -l patches \
  "VIEWONTAG" "PERTAG" "AUTOSTART" \
  "ATTACHBOTTOM" "ALWAYSCENTER" "ALT_TAB" \
  "VANITYGAPS" "XRDB" "MOVESTACK" "RESTARTSIG"

set -l patchfile $dwmflexdir/patches.def.h

for patch in $patches
  sed -i "s#define ${patch}_PATCH 0/s#define ${patch}_PATCH 1" $patchfile
end

cd $dwmflexdir
make && sudo make clean install
cd -

git clone https://github.com/bakkeby/flexipatch-finalizer.git $flexfinalizerdir
cd $flexfinalizerdir
./flexipatch-finalizer.sh -r -d $dwmflexdir -o $destdir

cd $destdir
make && sudo make clean install
