#!/usr/bin/env fish

argparse -i "h/help" -- $argv

type -q reflector || exit

if set -q _flag_help
  reflector --help | less && exit
end

sudo reflector -p https -l 5 --sort rate -c UA,PL \
  --verbose --save /etc/pacman.d/mirrorlist
