#!/usr/bin/env fish

argparse --ignore-unknown \
  "u/up" "d/down" "m/mute" "l/level=" "s/set=" -- $argv

not type -q pactl && exit

if set -q _flag_mute
  pactl set-sink-mute @DEFAULT_SINK@ toggle
  exit
end

if set -q _flag_set
  pactl set-sink-volume @DEFAULT_SINK@ "$_flag_set%"
  exit
end

if set -q _flag_level
  if set -q _flag_up
    pactl set-sink-volume @DEFAULT_SINK@ "+$_flag_level%"
  else if set -q _flag_down
    pactl set-sink-volume @DEFAULT_SINK@ "-$_flag_level%"
  end
end
